config/routes.rb
Rails.application.routes.draw do

  resources :lists, :only => [:index, :create, :update, :new]

  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/todoo.rb
class Todoo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def index

  end

  # def create
  #   @item = List.new(params[:item])
  #   p "*" * 100
  #   p params
  #   p "*" * 100
  #   @item.save!
  #   redirect_to lists_url
  # end

  # def show
  #   @todos = List.all
  # end

  # private
  #   def list_params
  #     params.require(:list).permit(:item, :done)
  #   end

end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @todos = List.order('id ASC')
  end

  def new

  end

  def create
    # binding.pry
    @single_todo = List.create(list_params)
    # respond_to do |format|
    #   if @single_todo.save
    #     format.html { redirect_to @single_todo, notice: "todo successfully created"}
    #     format.js {}
    #     format.json { render json: @single_todo, status: :created, location: @single_todo }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @single_todo.errors, status: :unprocessable_entity}
    #   end
    # end
    render json: @single_todo
  end

  def update
    @done = List.find(params[:id])
    if @done.update_attributes(:done => true)
      redirect_to lists_url
    end

    # respond_to do |format|
    #   format.html { redirect_to lists_url }
    #   format.js
    #   format.json { render json: @done}
    # end
  end

  private
    def list_params
      params.require(:list).permit(:item, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/landing_page/index.html.erb
<h1>LandingPage#index</h1>
<p>Find me in app/views/landing_page/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catie</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Cantarell:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_list.html.erb
<li><%= todo.item %></li>
<li><%= todo.id %></li>
<li><%= todo.done %></li>
<%= link_to("Done", list_path(todo.id), :done => true, :method => :put)%>

app/views/lists/create.html.erb
<p>create page</p>

app/views/lists/create.js.erb
// alert("create.js.erb");

$('ul').append("<%= j render partial: 'list', locals: {todo: @single_todo} %>")

app/views/lists/index.html.erb
<div class="col-md-4 col-md-offset-5">
  <h1>New Todo</h1>
  <div id="newtodoo">
  <%= form_for :list, :url => lists_path(), :method => :post  do |f| %>
    <p id="new_todo_form">
      <%= f.label :"What needs to be done?" %><br>
      <%= f.text_field :item, class: "item_title" %>
    </p>
    <p id="add_new_todo_submit">
      <%= f.hidden_field :done, :value => false %>
      <%= f.submit "Add New Todo", :class => "btn btn-secondary-outline" %>
    </p>
  <% end %>
  </div>
</div>
</div>

<h2 class="col-md-4 col-md-offset-5 text-left">All your todos</h2>
<div class="container_all_todos container col-md-4 col-md-offset-5">
  <% @todos.each do |todo| %>
    <ul class="col-sm-6">
      <li><%= todo.item %></li>
      <li><%= todo.done %></li>
        <p id="donee">
          <%= hidden_field :done, :value => true %>
          <%= link_to("Done", list_path(todo.id),:done => true, :method => :put)%>
        </p>
    </ul>
  <% end %>
</div>

<br><br>
<br><br>

app/views/lists/new.html.erb
<h1>New Todo</h1>
<div id="newtodoo">
<%= form_for :list, :url => lists_path(), :method => :post  do |f| %>
  <p>
    <%= f.label :item %><br>
    <%= f.text_field :item, class: "item_title" %>
  </p>
  <p id="addnew">
    <%= f.hidden_field :done, :value => false %>
    <%= f.submit("Add New Todo") %>
  </p>
<% end %>
</div>
<br><br>

app/views/lists/new.js.erb
$("#newtodo").hide().after("<%= j render('form') %>")

app/views/lists/update.html.erb
<%= @done.done %>

app/views/lists/update.js.erb
<% if @done.done == false %>
  $("#<%= todo.id %>").html("true");
  console.log("<%= todo.id %> is done?");
<% else %>
  $("#<%= todo.id %>").html("false");
  console.log("what happens here");
<% end %>

app/views/todos/index.html.erb
<h1>New Item</h1>
<%= form_for :todo do |f| %>
  <p>
    <%= f.label :todo %><br>
    <%= f.text_field :item %>
  </p>
  <p>
    <%= f.label :Done %><br>
    <%= f.text_field :item %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>